### ISSUE TITLE
Implementation Android Studio Bumblebee

### ISSUE THREAD

**Issue by ArleyPereira** [valkriaine/Bouncy#17]
Hello, I didn't find any updated walkthrough on how to add this library to my project, is there any tutorial?

**Comment by valkriaine** [comment]
> Hello, I didn't find any updated walkthrough on how to add this library to my project, is there any tutorial?

Hello! Sorry for the delay, the project has been updated, and please check README for how to add Bouncy to your project.

**Comment by valkriaine** [comment]
https://github.com/valkriaine/Bouncy#gradle
