### ISSUE TITLE
Holding the bounce position when dragging is not working

### ISSUE THREAD

**Issue by ach-ref** [valkriaine/Bouncy#8]
Hi,

I noticed when your drag the scrollview (up & down) it bounces perfectly but if you keep your finger down the scrollview doesn't stay in place, it goes back to the zero offset position with a very weird (choppy/jerky) animation.

In the meanwhile on an iOS device when you hold your finger down the scrollview  stays still until you take your finger up when it goes back to the initial position.

Than you,
Achref

**Comment by Valkriaine** [comment]
Thanks for the feedback, I will look into the issue

**Comment by erich04** [comment]
Same problem for me

**Comment by zhangyongbin-design** [comment]
I have the same problem.

**Comment by valkriaine** [comment]
> Hi,
> 
> I noticed when your drag the scrollview (up & down) it bounces perfectly but if you keep your finger down the scrollview doesn't stay in place, it goes back to the zero offset position with a very weird (choppy/jerky) animation.
> 
> In the meanwhile on an iOS device when you hold your finger down the scrollview stays still until you take your finger up when it goes back to the initial position.
> 
> Than you, Achref



> Same problem for me



> I have the same problem.



> This problem still exists for me.


Hello, sorry for the delay. This is now resolved in the newest build. 

Thank you for your support!

**Comment by longshishui** [comment]
已收到阁下的来件 我会尽早回复的
